apiVersion: v1
kind: Service
metadata:
  name: postgres-write
  labels:
    app: postgres
    role: write
spec:
  selector:
    app: postgres
    role: master
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-read
  labels:
    app: postgres
    role: read
spec:
  selector:
    app: postgres
    role: slave
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP
