apiVersion: v1
kind: Service
metadata:
  name: postgres-slave
  labels:
    app: postgres
    role: slave
spec:
  selector:
    app: postgres
    role: slave
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      name: postgres
  type: ClusterIP
