apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: products-microservice

resources:
  - mongodb-deployment.yaml
  - mongodb-service.yaml
  - products-deployment.yaml
  - products-service.yaml
  - products-hpa.yaml
