apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Aguardando MongoDB..."
              until nc -z mongodb 27017; do
                echo "MongoDB ainda não está pronto..."
                sleep 2
              done
              echo "MongoDB está pronto!"
      containers:
        - name: products
          image: products-microservice:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50051
              name: grpc
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:mongo@mongodb:27017/productsdb?authSource=admin"
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
